### ISSUE TITLE
Argonaut Debian Repository URL: 404 Not Found

### ISSUE THREAD

**Issue by chk2k2** [fusiondirectory/fusiondirectory-user-manual#1]
Hi!

The repository URL given in https://fusiondirectory-user-manual.readthedocs.io/en/1.3/argonaut/repositories/debian.html does not exist. Server answers 404 Not Found.

What is the correct argonaut repo URL?
Thanks

Christian

**Comment by bilbo-the-hobbit** [comment]
Hello @chk2k2 

Thank you for your patience, Argonaut is no longer maintained and has been archived, its replacement is FusionDirectory Orchestrator that will gradually get all the Argonaut functionalities

Cheers
