### ISSUE TITLE
Wrong command in "Check for deprecated attributes" section of migration guide from 1.3.-1 to 1.4

### ISSUE THREAD

**Issue by eickeh** [fusiondirectory/fusiondirectory-user-manual#2]
Not sure if that's the right place for this, but [in the docs of the migration guide from 1.3.-1 to 1.4](https://fusiondirectory-user-manual.readthedocs.io/en/latest/fusiondirectory/update/supported/1.3-1-to-1.4.html) are some small mistakes in the text. The corresponding code sections are however correct (although some of them are only mentioned in the text):
- The mentioning of `fusiondirectory-configuration-manager –list-deprecated` should be `fusiondirectory-migration-manager --list-deprecated` (i.e. 'migration' instead of 'configuration' and a second dash)
- The following commands miss the second dash in the option:
  - `fusiondirectory-migration-manager –check-deprecated`
  - `fusiondirectory-migration-manager –ldif-deprecated`
  - `fusiondirectory-migration-manager –check-deprecated`
  - `fusiondirectory-migration-manager –remove-supann-root`
  - `fusiondirectory-migration-manager –migrate-interfaces`

**Comment by bilbo-the-hobbit** [comment]
Hello @eickeh 

a ticket has been opened in our gitlab to follow the resolution of this ticket

https://gitlab.fusiondirectory.org/fusiondirectory/user-manual/-/issues/249

Cheers

**Comment by bilbo-the-hobbit** [comment]
Thank you for your contribution, the fixed version is now in the documentation

Cheers
