### ISSUE TITLE
Wrong commands in latest/fusiondirectory/plugins/ipam/installation.html

### ISSUE THREAD

**Issue by JennyHo5** [fusiondirectory/fusiondirectory-user-manual#3]
Hi,

When following this [page](https://fusiondirectory-user-manual.readthedocs.io/en/latest/fusiondirectory/plugins/ipam/installation.html) to install the ipam schema package on Debian, I got an error from apt complaining about `Unable to locate package fusiondirectory-plugin-ipam-fd.schema`, so I assume the package name is wrong.

Instead of: `apt-get install fusiondirectory-plugin-ipam-fd.schema`

It should be: `apt-get install fusiondirectory-plugin-ipam-schema`

I assume the name is also wrong for RHEL. 

Thanks!

**Comment by bilbo-the-hobbit** [comment]
Hello @JennyHo5 

Thanks for the report, I just fixed it in the documentation. It should appear soon

https://gitlab.fusiondirectory.org/fusiondirectory/user-manual/-/issues/259
